# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MEa2zoQXG9zyPpvqrcGs5Lxupp51ReAP
"""

menu = ["Kopi Susu", "Matha Latte", "Americano"]
harga = [18000, 22000, 15000]
jumlah = [4, 3, 5]
sub_total = harga[0] * jumlah[0]
sub_total = 72000
sub_total = harga[1] * jumlah[1]
sub_total = 66000
sub_total = harga[2] * jumlah[2]
sub_total = 75000
sub_kopi = 72000
sub_matha = 66000
sub_americano = 75000
subtotal_pendapatan = sub_kopi + sub_matha + sub_americano
subtotal_pendapatan
subtotal_pendapatan = 213000
total_seluruh = 213000
subtotal_pendapatan = total_seluruh
BIAYA_OPERASIONAL = 15000
pendapatan_bersih = total_seluruh - BIAYA_OPERASIONAL
pendapatan_bersih = 198000
jumlah_barang = 4 + 3 + 5
jumlah_barang = 12
target_tercapai = (subtotal_pendapatan > 200000 and jumlah_barang > 10)
target_tercapai = True or False
target_tercapai = True
print(subtotal_pendapatan)
print(pendapatan_bersih)
print(target_tercapai)
213000
198000
True